企業情報の紐付け、企業マスタの設定
CoopTechOrg/WebERP pull request #71
Opened 2022-02-27 14:04 UTC by Zuzu0725

## チケットへのリンク

https://redmine.cooptech.biz/issues/53

## やったこと

* companyモデル作成
* 企業用のマイグレーション作成（create_companies_table.php）
* ユーザー用のマイグレーション追加(add_column_to_users_table.php）
* ユーザーと企業のリレーション設定

2022-02-28 03:27 UTC, cresta522 requested changes

2022-02-28 03:27 UTC, cresta522 commented on src/app/Models/Company.php
> +    public function users()
返り値の指定をお願いしますー

2022-02-28 03:27 UTC, cresta522 commented on src/app/Models/User.php
> +    public function company()
返り値の指定をお願いしますー

2022-02-28 12:37 UTC, Zuzu0725 commented
返り値の指定と、use文追加しました。

2022-02-28 13:21 UTC, cresta522 requested changes

2022-02-28 13:21 UTC, cresta522 commented on src/app/Models/Company.php
> +    public function users(): HasMany
HasManyのクラスがuseされてないようですが特に動作上問題ないですか？

2022-02-28 14:45 UTC, Zuzu0725 commented on src/app/Models/Company.php
> +    public function users(): HasMany
HasManyクラス必要でした。
追加します。

2022-02-28 14:47 UTC, cresta522 requested changes

2022-02-28 14:47 UTC, cresta522 commented on src/app/Http/Controllers/UserController.php
> +use App\Models\Company;
このControllerで使用していないのであればuseは不要です。

2022-02-28 14:47 UTC, cresta522 commented on src/app/Models/User.php
> +    public function company(): BelongsTo
BelongsToのクラスがuseされてないようですが特に動作上問題ないですか？

2022-03-17 12:12 UTC, cresta522 approved these changes

2022-03-17 12:12 UTC, merged