Feature/#105
CoopTechOrg/WebERP pull request #77
Opened 2022-08-21 10:39 UTC by Rywwwwwww

2022-09-02 19:41 UTC, Rywwwwwww commented
estimateテーブルにデータ登録処理＆インデント修正しました

2022-09-05 11:51 UTC, cresta522 requested changes

2022-09-05 11:51 UTC, cresta522 commented on src/database/migrations/2022_08_30_185857_add_no_to_estimate_details_table.php
> +            });
マイグレーションは追加ファイルじゃなくて、既存の`estimate_details`に追記してください

2022-09-05 11:51 UTC, cresta522 commented on src/app/Http/Controllers/EstimateController.php
> +        return view("/estimate/index");
/ でディレクトリ階層を表記せず、 `.` でディレクトリ階層を指定してください

2022-09-05 11:51 UTC, cresta522 commented on src/app/Http/Controllers/EstimateController.php
>          //リダイレクト(後でリダイレクト先変更する)
`//` の後ろはスペース一つ開けて統一してください。。

2022-09-05 11:51 UTC, cresta522 commented on src/app/Http/Controllers/EstimateController.php
> +        //DB::table("products")->insert($products_sql);
コメントは削除するのと、変数はキャメルでお願いします。

2022-09-05 11:51 UTC, cresta522 commented on src/app/Http/Controllers/EstimateController.php
> +        $estimates_sql = [
変数名が不適です。
リクエストは独自のリクエストクラスを作成して対応してください。
内容はゲッターで取得です。

2022-09-05 11:52 UTC, cresta522 requested changes

2022-09-05 11:52 UTC, cresta522 commented on src/app/Http/Controllers/EstimateController.php
>  		"updated_by" => 0,
更新者もログインユーザです。

2022-09-05 11:53 UTC, cresta522 requested changes

2022-09-05 11:53 UTC, cresta522 commented on src/database/factories/UserFactory.php
> +>>>>>>> c881ea3c2e7f63e9cc1788d1a6f5584fdaf622cb
コンフリクト履歴は上げないでくださいー

2022-09-05 11:56 UTC, cresta522 requested changes

2022-09-05 11:56 UTC, cresta522 commented on src/resources/views/estimate/create.blade.php
> +    <form action="{{url('estimate/index')}}" method="post" class="estimate__container">
actionは `route` 関数を利用して、ルーティングと紐づけてください

2022-09-05 11:56 UTC, cresta522 commented on src/resources/views/estimate/create.blade.php_backup
>                              <label for="clients" class="detail_label require">取引先</label>
バックアップファイルはpushしないでください、、

2022-09-05 11:56 UTC, cresta522 commented on src/routes/web.php
> +    Route::post('/estimate/index', [EstimateController::class, 'store']);
indexへはpostしないでください。
また、indexはURLに記載しないということもありますしアクションがstoreなら不適なURLです

2022-09-10 07:55 UTC, Rywwwwwww commented
20220910　上記修正しました

2022-09-10 08:25 UTC, cresta522 requested changes

2022-09-10 08:25 UTC, cresta522 commented on src/app/Http/Controllers/EstimateController.php
> +        $Estimates = [
命名規約が間違っていますー。
キャメルorスネークです。

2022-09-10 08:25 UTC, cresta522 commented on src/app/Http/Controllers/EstimateController.php
> +        return view(".estimate.index");
これは多分動作ができない気がしますが、動作確認できましたか？

2022-09-10 08:25 UTC, cresta522 commented on src/app/Http/Requests/EstimateRequest.php
> +    public function authorize()
返り値指定してください。

2022-09-10 08:25 UTC, cresta522 commented on src/database/migrations/2022_04_04_145718_create_estimate_details_table.php
> +            $table->string('no')->comment('見積もり番号')->nullable(false)->unique(); //明細の番号
明細の行番号は数値です。

2022-09-10 08:25 UTC, cresta522 commented on src/resources/views/estimate/create.blade.php
> +    <form action="{{route('estimate.store')}}" method="post" class="estimate__container">
phpstormに倣って↓に合わせましょう。
`{{ route('estimate.store') }}`

2022-09-17 22:18 UTC, Rywwwwwww commented
修正しました

2022-09-18 02:41 UTC, cresta522 approved these changes

2022-09-18 02:41 UTC, merged